### PR TITLE
Do not warn on custom properties

### PR DESCRIPTION
**Pull request by 616slayer616**

### CODE REVIEW

**Comment by 4braincells** [comment]
Hi, any idea if this will make it into maven repo? :-D
I dont like self-built-forked-repo-libs which will break dependencies one day.
I had to do this once with IBANs ...

**Comment by 616slayer616** [comment]
Hi
It seems I forgot to release this.
Will do it within the day

**Comment by 616slayer616** [comment]
Now that I look at it it seems that it is already present in 1.7.0

**Comment by 4braincells** [comment]
In #49 you mentioned that this could solve the CSS issue ...

**Comment by 616slayer616** [comment]
Ah this is about the gradle minify plugin.
Now I understand.
I released that with the new version

**Comment by 4braincells** [comment]
Thanks a lot for the quick reaction :-)
It worked perfectly already, now it works perfectly silent, too :-D

**Comment by 616slayer616** [comment]
Good to know.
Sorry it took so long.

**Pull request merged**
